server:
  port: 9000
  
spring:  application:    name: gateway-service  cloud:    gateway:      routes:
      - id: userMicroService
        uri: http://localhost:9090/
        predicates:
        - Path=/user/**
      - id: appMicroService
        uri: http://localhost:9091/
        predicates:
        - Path=/tc/**
          devtools:    add-properties: false